### ISSUE TITLE
How can I change the standard search engine in Firefox/Chrome Empty Start Page to Yacy

### ISSUE THREAD

**Issue by mariobehling** [yacy/YaCyBar#1]
If there is an empty page in a new tab there is a search page.

How can this search page be changed to Yacy?

![screenshot from 2016-09-03 20 11 06](https://cloud.githubusercontent.com/assets/1583873/18226845/d2f72e9a-7212-11e6-8376-d2a8efff675e.png)

**Comment by luccioman** [comment]
You first have to open a YaCy peer main search page and add it to your browser search engines list as with any OpenSearch compliant engine :
- Firefox : using for example the green "+" button in the search field
- Chrome : using settings (URL : chrome://settings/) and "Manage search engines..." button.

Once your YaCy peer is in the list, you have to set it as the default search engine :
- Firefox : using preferences (URL : about:preferences#search). Select "YaCy search on 'yourpeer'" in the default search engine combobox
- Chrome : using "Manage search engines..." button, in the open popup select the line with your YaCy peer and use the "Make default" button.

Then, when you will type something in the address bar or in the search field of a new tab, the search will be performed on YaCy!

**Comment by mariobehling** [comment]
@luccioman Thank you!

But, I should have specified my question more in detail. I would rather like to know how I can do that by providing a plugin that we could offer for users. I will follow up in a dedicated issue then. Cheers.

**Comment by luccioman** [comment]
Ok @mariobehling, no problem! But are you sure you really need a plugin? YaCy is using an OpenSearch descriptor, and among other things, OpenSearch is especially designed to offer a generic way to add search engines to browsers...
